# Generated by Django 5.2.6 on 2025-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='gpio_pin',
            field=models.IntegerField(blank=True, help_text='Nomor pin GPIO BCM yang terhubung ke aktuator loker ini', null=True),
        ),
    ]
