# Generated by Django 5.2.6 on 2025-11-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_locker_gpio_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='blynk_device_token',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='blynk_vpin_control',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='blynk_vpin_sensor',
        ),
    ]
