# Generated by Django 5.2.6 on 2025-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='transaction',
                    name='buyer_full_name',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='buyer_phone_number',
                    field=models.CharField(blank=True, max_length=32),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='otp_code',
                    field=models.CharField(blank=True, db_column='otp', max_length=6),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='payment_proof',
                    field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='payment_proof_uploaded_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='paid_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='payment_expires_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='qris_image',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='qris_payload',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='shipping_address',
                    field=models.TextField(blank=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('ESCROW', 'Escrow'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('RELEASED', 'Escrow Released'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
