# Generated by Django 5.2.6 on 2025-11-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_image'),
        ('marketplace', '0004_transaction_shipping_otp'),
    ]

    operations = [
    ]
