# Generated by Django 5.2.6 on 2025-11-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_merge_20251109_1715'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='transaction',
                    name='otp_code',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='qris_images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qris_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
