# Generated by Django 5.2.6 on 2025-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_transaction_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('NEED_VERIFICATION', 'Need Verification'), ('PAID', 'Paid'), ('ESCROW', 'Escrow'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('RELEASED', 'Escrow Released'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
