# Generated by Django 5.2.6 on 2025-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
