# Generated by Django 5.2.6 on 2025-11-11 10:26

from django.db import migrations, models


def normalize_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    mapping = {
        'BUYER': 'buyer',
        'buyer': 'buyer',
        'OWNER': 'owner',
        'owner': 'owner',
        'SELLER': 'owner',
        'seller': 'owner',
        'COURIER': 'courier',
        'courier': 'courier',
        'ADMIN': 'admin',
        'admin': 'admin',
    }
    for legacy, normalized in mapping.items():
        User.objects.filter(role=legacy).update(role=normalized)


def revert_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    reverse_mapping = {
        'buyer': 'BUYER',
        'owner': 'OWNER',
        'courier': 'COURIER',
        'admin': 'ADMIN',
    }
    for current, legacy in reverse_mapping.items():
        User.objects.filter(role=current).update(role=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('owner', 'Owner'), ('courier', 'Courier'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
        migrations.RunPython(normalize_roles, revert_roles),
    ]
