# Generated by Django 5.2.6 on 2025-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='First name (required for OWNER role)', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Last name (required for OWNER role)', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_id',
            field=models.CharField(blank=True, editable=False, help_text='Unique ID for face recognition (OWNER only)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('COURIER', 'Courier'), ('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin')], default='BUYER', max_length=10),
        ),
    ]
