# Generated by Django 5.2.6 on 2025-10-26 15:05

import django.db.models.deletion
import apps.facerecognition.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_options_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datawajahnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_user', models.ImageField(blank=True, help_text='Face image for training', null=True, upload_to=apps.facerecognition.models.upload_image_training2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Must be a user with OWNER role', limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Wajah',
                'verbose_name_plural': 'Data Wajah',
            },
        ),
        migrations.CreateModel(
            name='Logsmartaccess2',
            fields=[
                ('log_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=apps.facerecognition.models.upload_image_access_user)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('id_face_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_access_user', to=settings.AUTH_USER_MODEL, to_field='face_id')),
            ],
        ),
    ]
