# Generated by Django 5.2.6 on 2025-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_remove_face_match_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotevent',
            name='event_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('DEVICE', 'Device Event'), ('LOCKER_OPENED', 'Locker Opened'), ('ITEM_DETECTED', 'Item Detected')], default='GENERIC', max_length=50),
        ),
    ]
